modify yml file

diff --git a/.azure/pipeline/azure-reusable-build.yml b/.azure/pipeline/azure-reusable-build.yml
--- a/.azure/pipeline/azure-reusable-build.yml
+++ b/.azure/pipeline/azure-reusable-build.yml
@@ -3,163 +3,256 @@
 
 # This workflow performs a build of the project and uploads the result as a build artifact.
 
-parameters:
-  # Name associated with the output of this build.
-  - name: build_artifact
-    type: string
-  # Name of the job
-  - name: name
-    type: string
-  # Additional options passed to msbuild.
-  - name: build_options
-    type: string
-    default: ''
-  - name: generate_release_package
-    type: boolean
-    default: false
-  - name: build_codeql
-    type: boolean
-    default: false
-  - name: build_nuget
-    type: boolean
-    default: false
-  - name: cxx_flags
-    type: string
-    default: ''
-  - name: ld_flags
-    type: string
-    default: ''
+name: Reusable MSBuild Workflow
+
+on:
+  workflow_call:
+    inputs:
+      # Name associated with the output of this build.
+      build_artifact:
+        required: true
+        type: string
+      # Additional options passed to msbuild.
+      build_options:
+        required: false
+        type: string
+      generate_release_package:
+        required: false
+        type: boolean
+      build_codeql:
+        required: false
+        type: boolean
+      build_msi:
+        required: false
+        type: boolean
+      build_nuget:
+        required: false
+        type: boolean
+      cxx_flags:
+        required: false
+        type: string
+      ld_flags:
+        required: false
+        type: string
+      configurations:
+        required: false
+        type: string
+        default: '["Debug", "Release"]'
+
+permissions:
+  contents: read
+  security-events: write # Required by codeql task
 
 jobs:
-  - job: '${{parameters.name}}'
-    timeoutInMinutes: 90
+  build:
+    timeout-minutes: 90
 
     strategy:
       matrix:
-        Debug:
-          buildConfiguration: 'Debug'
-        Release:
-          buildConfiguration: 'Release'
-      maxParallel: 2
-
-    pool:
-      vmImage: 'windows-2022'
-      type: windows
-
-    variables:
+        configurations: ${{ fromJSON(inputs.configurations) }}
+    runs-on: windows-2022
+    env:
       # Path to the solution file relative to the root of the project.
       SOLUTION_FILE_PATH: ebpf-for-windows.sln
-      BUILD_ARTIFACT_NAME: ${{parameters.build_artifact}}
-      BUILD_CONFIGURATION: $(buildConfiguration)
+      BUILD_ARTIFACT_NAME: ${{inputs.build_artifact}}
+      BUILD_CONFIGURATION: ${{matrix.configurations}}
       BUILD_PLATFORM: x64
-      BUILD_OPTIONS: ${{parameters.build_options}}
-      CXX_FLAGS: ${{parameters.clxx_flags}}
-      LD_FLAGS: ${{parameters.ld_flags}}
-      MSBUILD_PATH: 'C:\Program Fies\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64'
-      GDN_CODESIGN_TARGETDIRECTORY: '$(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)'
+      BUILD_OPTIONS: ${{inputs.build_options}}
+      CXX_FLAGS: ${{inputs.cxx_flags}}
+      LD_FLAGS: ${{inputs.ld_flags}}
 
     steps:
-      - checkout: self
-        displayName: 'Checkout Repo'
+    - id: skip_check
+      uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0
+      with:
+        cancel_others: 'false'
+        paths_ignore: '["**.md", "**/docs/**"]'
+
+    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
+      if: steps.skip_check.outputs.should_skip != 'true'
+      with:
         submodules: 'recursive'
-        fetchDepth: 0
 
-      - bash: |
-          echo "*** All environment variables ***"
-          env | sort
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Dump Environment variables'
+    - name: Configure Windows Error Reporting to make a local copy of any crashes that occur.
+      id: configure_windows_error_reporting
+      if: steps.skip_check.outputs.should_skip != 'true'
+      run: |
+        mkdir c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+        New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -ErrorAction SilentlyContinue
+        New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Name "DumpType" -Value 2 -PropertyType DWord -ErrorAction SilentlyContinue
+        New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Name "DumpFolder" -Value "c:\dumps\${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}}" -PropertyType ExpandString -ErrorAction SilentlyContinue
 
-      - bash: |
-          choco install -y llvm --version 11.0.1 --allow-downgrade
-          echo '##vso[task.prependpath]C:\Program Files\LLVM\bin'
-          choco install wixtoolset
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName:  'Install tools'
+    - name: Initialize CodeQL
+      if: inputs.build_codeql == true && steps.skip_check.outputs.should_skip != 'true'
+      uses: github/codeql-action/init@29b1f65c5e92e24fe6b6647da1eaabe529cec70f
+      with:
+        languages: 'cpp'
 
-      - task: NuGetCommand@2
-        inputs:
-          command: 'restore'
-          restoreSolution: $(SOLUTION_FILE_PATH)
-        displayName: 'Restore Nuget Packages'
+    - name: Add MSBuild to PATH
+      uses: microsoft/setup-msbuild@1ff57057b5cfdc39105cd07a01d78e9b0ea0c14c
 
-      - bash: |
-          cmake -G "Visual Studio 17 2022" -S external/ebpf-verifier -B external/ebpf-verifier/build
-        env:
-          CXXFLAGS: '$(CXX_FLAGS) /ZH:SHA_256'
-          LDFLAGS: $(LD_FLAGS)
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Create verifier project'
+    - name: Setup choco cache folder
+      # Set the choco cache to a local folder so that it can be cached.
+      if: steps.skip_check.outputs.should_skip != 'true'
+      id: choco-cache
+      run: |
+        mkdir ${{github.workspace}}\choco_cache
+        choco config set --name cacheLocation --value ${{github.workspace}}\choco_cache
 
-      - bash: |
-          cmake -G "Visual Studio 17 2022" -S external/catch2 -B external/catch2/build -DBUILD_TESTING=OFF
-        env:
-          CXXFLAGS: '$(CXX_FLAGS) /ZH:SHA_256'
-          LDFLAGS: $(LD_FLAGS)
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Create catch2 project'
+    - name: Cache choco packages
+      # Add cache entry for any choco packages that are installed.
+      # The cache key is based on the hash of this file so if any choco packages are added or removed, the cache will be invalidated.
+      if: steps.skip_check.outputs.should_skip != 'true'
+      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
+      env:
+        cache-name: cache-choco-packages
+      with:
+        path: ${{github.workspace}}\choco_cache
+        key: ${{ hashFiles('.github/workflows/reusable-build.yml') }}
 
-      - bash: |
-          cmake -G "Visual Studio 17 2022" -S external/ubpf -B external/ubpf/build
-        env:
-          CXXFLAGS: '$(CXX_FLAGS) /ZH:SHA_256'
-          LDFLAGS: $(LD_FLAGS)
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Create ubpf project'
+    - name: Install tools
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: |
+        choco install -y llvm --version 11.0.1 --allow-downgrade
+        echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
-      - script: |
-          "$(MSBUILD_PATH)\msbuild.exe" /m /p:Configuration=$(BUILD_CONFIGURATION) /p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE_PATH) $(BUILD_OPTIONS)
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Build'
+    - name: Cache nuget packages
+      if: steps.skip_check.outputs.should_skip != 'true'
+      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
+      env:
+        cache-name: cache-nuget-modules
+      with:
+        path: packages
+        key: ${{ runner.os }}-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}-${{env.BUILD_ARTIFACT_NAME}}-${{ hashFiles('**/packages.config') }}
 
-      - script: |
-          copy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\clang*" .
-        workingDirectory: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
-        displayName: 'Copy LLVM libs for Fuzzing & Address Sanitizing'
+    - name: Restore NuGet packages
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
 
-      - powershell: |
-          Invoke-WebRequest https://github.com/microsoft/ebpf-for-windows-demo/releases/download/v0.0.1/$(BUILD_PLATFORM)-$(BUILD_CONFIGURATION)-cilium-xdp.zip -OutFile x64-$(BUILD_CONFIGURATION)-cilium-xdp.zip
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Download demo repository'
+    - name: Cache verifier project
+      # The hash is based on the HEAD of the ebpf-verifier submodule, the Directory.Build.props file, and the build variant.
+      if: steps.skip_check.outputs.should_skip != 'true'
+      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
+      env:
+        cache-name: cache-verifier-project
+      with:
+        path: external/ebpf-verifier/build
+        key: ${{ runner.os }}-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}-${{env.BUILD_ARTIFACT_NAME}}-${{ hashFiles('.git/modules/external/ebpf-verifier/HEAD') }}-${{ hashFiles('external/Directory.Build.props')}}
 
-      - script: |
-          tar -xf ..\..\x64-$(BUILD_CONFIGURATION)-cilium-xdp.zip
-        workingDirectory: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
-        displayName: 'Extract artifacts to build path'
+    - name: Create verifier project
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      env:
+        CXXFLAGS: /ZH:SHA_256 ${{env.CXX_FLAGS}}
+        LDFLAGS: ${{env.LD_FLAGS}}
+      run: |
+        cmake -G "Visual Studio 17 2022" -S external\ebpf-verifier -B external\ebpf-verifier\build
 
-      - publish: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
-        artifact: "${{parameters.build_artifact}} $(buildConfiguration)"
-        displayName: 'Upload Build Output'
+    - name: Create catch2 project
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      env:
+        CXXFLAGS: /ZH:SHA_256 ${{env.CXX_FLAGS}}
+        LDFLAGS: ${{env.LD_FLAGS}}
+      run: |
+        cmake -G "Visual Studio 17 2022" -S external\catch2 -B external\catch2\build -DBUILD_TESTING=OFF
 
-      - publish: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)/ebpf-for-windows.msi
-        artifact: "ebpf-for-windows MSI installer $(buildConfiguration)"
-        condition: and(eq('${{parameters.build_artifact}}', 'Build-x64'), eq(variables.buildConfiguration, 'Debug'))
-        displayName: 'Upload the MSI package (Debug)'
+    - name: Create ubpf project
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      env:
+        CXXFLAGS: /ZH:SHA_256 ${{env.CXX_FLAGS}}
+        LDFLAGS: ${{env.LD_FLAGS}}
+      run: |
+        cmake -G "Visual Studio 17 2022" -S external\ubpf -B external\ubpf\build
 
-      - publish: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)/ebpf-for-windows.msi
-        artifact: "ebpf-for-windows MSI installer $(buildConfiguration)"
-        condition: and(eq('${{parameters.build_artifact}}', 'Build-x64'), eq(variables.buildConfiguration, 'Release'))
-        displayName: 'Upload the MSI package (Release)'
-      - script: |
-          Start-Process -Wait 'C:\Windows\system32\msiexec.exe /i (Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)/ebpf-for-windows.msi INSTALLFOLDER="C:\Program Files\ebpf-for-windows" ADDLOCAL=eBPF_Runtime_Components,eBPF_Runtime_Components_JIT,eBPF_Development,eBPF_Testing /qn'
-      - script: |
-          "$(MSBUILD_PATH)\msbuild.exe" /m /p:Configuration="$(BUILD_CONFIGURATION)" /p:Platform="$(BUILD_PLATFORM)" "$(SOLUTION_FILE_PATH)" "$(BUILD_OPTIONS)" /t:tools\nuget
-        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'))
-        workingDirectory: $(Build.SourcesDirectory)
-        displayName: 'Build nuget package'
+    - name: Build
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.BUILD_OPTIONS}} ${{env.SOLUTION_FILE_PATH}}
 
-      - bash: |
-          echo "##vso[task.setvariable variable=REL_NUGET_PACKAGE_PATH;isOutput=true]$(ls $(BUILD_PLATFORM)/$(BUILD_CONFIGURATION)/*.nupkg)"
-        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'))
-        name: nuget_packages
-        displayName: 'Locate the nuget package'
+    - name: Copy LLVM libs for Fuzzing & Address Sanitizing
+      if: steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+      run: copy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\clang*" .
 
-      - publish: $(nuget_packages.REL_NUGET_PACKAGE_PATH)
-        artifact: 'ebpf-for-windows nuget'
-        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'), eq('${{parameters.build_artifact}}', 'Build-x64'))
-        displayName: 'Upload the nuget package'
+    - name: Download demo repository
+      if: steps.skip_check.outputs.should_skip != 'true' && matrix.configurations != 'FuzzerDebug'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: Invoke-WebRequest https://github.com/microsoft/ebpf-for-windows-demo/releases/download/v0.0.1/${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}-cilium-xdp.zip -OutFile x64-${{env.BUILD_CONFIGURATION}}-cilium-xdp.zip
 
-      - publish: $(nuget_packages.REL_NUGET_PACKAGE_PATH)
-        artifact: 'ebpf-for-windows-native nuget'
-        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'), eq('${{parameters.build_artifact}}', 'Build-x64-native-only'))
-        displayName: 'Upload the nuget package'
+    - name: Extract artifacts to build path
+      if: steps.skip_check.outputs.should_skip != 'true' && matrix.configurations != 'FuzzerDebug'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: |
+        cd ${{github.workspace}}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+        tar -xf ..\..\x64-${{ matrix.configurations }}-cilium-xdp.zip
+
+    - name: Zip Build Output
+      if: always() && (steps.skip_check.outputs.should_skip != 'true')
+      working-directory: ${{github.workspace}}
+      run: |
+        Compress-Archive -Path ${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}} -DestinationPath .\build-${{ matrix.configurations }}.zip
+
+    - name: Upload Build Output
+      if: always() && (steps.skip_check.outputs.should_skip != 'true')
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+      with:
+        name: ${{inputs.build_artifact}}-${{matrix.configurations}}
+        path: ${{github.workspace}}/build-${{ matrix.configurations }}.zip
+        retention-days: 5
+
+    - name: Upload the MSI package
+      if: inputs.build_msi == true
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+      with:
+        name: ebpf-for-windows - MSI installer (${{inputs.build_artifact}}_${{env.BUILD_CONFIGURATION}})
+        path: ${{github.workspace}}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/ebpf-for-windows.msi
+
+    - name: Build the NuGet package
+      if: inputs.build_nuget == true && matrix.configurations == 'Release' && steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}} ${{env.BUILD_OPTIONS}} /t:tools\nuget
+
+    - name: Upload the NuGet package
+      if: inputs.build_nuget == true && matrix.configurations == 'Release' && steps.skip_check.outputs.should_skip != 'true'
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+      with:
+        name: ebpf-for-windows - NuGet package (${{inputs.build_artifact}}_${{env.BUILD_CONFIGURATION}})
+        path: ${{github.workspace}}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/eBPF-for-Windows.*.nupkg
+
+    - name: Build the NuGet Redist package
+      if: inputs.build_nuget == true && matrix.configurations == 'Release' && steps.skip_check.outputs.should_skip != 'true'
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}} ${{env.BUILD_OPTIONS}} /t:tools\redist-package
+
+    - name: Upload the NuGet Redist package
+      if: inputs.build_nuget == true && matrix.configurations == 'Release' && steps.skip_check.outputs.should_skip != 'true'
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+      with:
+        name: ebpf-for-windows - NuGet Redist package (${{inputs.build_artifact}}_${{env.BUILD_CONFIGURATION}})
+        path: ${{github.workspace}}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/eBPF-for-Windows-Redist.*.nupkg
+
+    - name: Check for crash dumps
+      # Check for crash dumps even if the workflow failed.
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true')
+      uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b
+      id: check_dumps
+      with:
+        files: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/*.dmp
+
+    - name: Upload any crash dumps
+      # Upload crash dumps even if the workflow failed.
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && (steps.check_dumps.outputs.files_exists == 'true')
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+      id: upload_crash_dumps
+      with:
+        name: Crash-Dumps-${{env.NAME}}-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}
+        path: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+        retention-days: 5
+
+    - name: Perform CodeQL Analysis
+      if: inputs.build_codeql == true && steps.skip_check.outputs.should_skip != 'true'
+      uses: github/codeql-action/analyze@29b1f65c5e92e24fe6b6647da1eaabe529cec70f
